AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String

  LogBucketName:
    Type: String    

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogBucketName
      AccessControl: Private
      
      
Outputs:
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
    
  S3BucketName:
    Value: !Ref S3Bucket